import img from './images/infomine.jpg';

export default [
    {
        id:"1",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"2",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"3",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"4",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"5",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"6",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
    {
        id:"7",
        name:"",
        publishedBy:"",
        publishedOn:"",
        slug:"",
        description:"",
        image:img
    },
]